name: Deploy Python SDK to Artifactory

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Make sure this includes build and twine if not installing separately

      - name: Build Wheells
        run: |
          python -m pip install build
          python -m build --wheel
          ls -l dist/
